[window]
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
# TODO: Specify bold, italic and bold_italic too!

[cursor]
style = { shape = "Block", blinking = "On" }

# TODO: Specify the colors!

