# Sets the theme
general.import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[window]
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }

[cursor]
style = { shape = "Block", blinking = "On" }

[env]
term = "alacritty-direct"
