# Disable the blank line at the start of the prompt.
add_newline = false

# Default Prompt Format.
format = "$directory$git_branch$git_status$character"

# Set Catppuccin Mocha as custom color palette.
palette = "catppuccin_mocha"

[directory]
style = "bold blue"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "foreground"

[git_status]
style = "red"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# Define Catppuccin Mocha color palette.
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#4b4b4b"
surface0 = "#363636"
base = "#222222"
mantle = "#1a1a1a"
crust = "#11111b"
