theme = "catppuccin_mocha"

[editor]
true-color = true
bufferline = "multiple"
line-number = "relative"
mouse = false

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "version-control", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "file-line-ending"]

[editor.indent-guides]
render = true

# TODO: Consider to use these keymaps in SELECT mode
[keys.normal]
# Move line(s) up
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
# Move line(s) down
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
