theme = "catppuccin_mocha"

[editor]
true-color = true
bufferline = "multiple"
line-number = "relative"
mouse = true
shell = ["fish", "-c"]

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "version-control", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "file-line-ending"]

[editor.indent-guides]
render = true

#################### Custom keybindings ####################
[keys.normal.space]
# TODO: Add keymap description.
# Open the Yazi file manager in the root directory.
e = [":new", ":insert-output tmux new-window -n yazi 'yazi'", ":buffer-close!", ":redraw"]
# Open the Glow markdown viewer.
m = [":new", ":insert-output tmux new-window -n glow 'glow'", ":buffer-close!", ":redraw"]
# Open search and replace tool.
C-f = [":new", ":insert-output tmux new-window -n serpl 'serpl'", ":buffer-close!", ":redraw"]

[keys.normal]
# TODO: Move the following two keymaps to visual mode!
# Move line(s) up.
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
# Move line(s) down.
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
################# End of custom keybindings #################
