[[language]]
name = "cpp"
formatter = { command = "clang-format" }

[language-server.clangd]
args = [ "--compile-commands-dir=./build" ]

[language.debugger]
name = "lldb-vscode"
transport = "stdio"
command = "lldb-vscode"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", runInTerminal = true }
